### ISSUE TITLE
React Table: Add more information

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#136]
@seanforyou23 I'm concerned that some users may not know what a Prop is, and so I'm wondering if we should add a hint or something underneath this code to show how a prop fits into a component?

I can add the change, what are your thoughts?

<img width="371" alt="Screen Shot 2019-10-31 at 1 53 26 PM" src="https://user-images.githubusercontent.com/20118816/67972859-dcae3e00-fbe5-11e9-9d29-2020011dc598.png">

**Comment by seanforyou23** [comment]
I can add an example below if you like, however we do already make a point to introduce the user to props on [step 4](https://github.com/patternfly/training-scenarios/blob/master/tables/intro-table/step4.md) which is the first time it is encountered.

I did spend some time pondering on how to best treat these types of details. One of the conclusions I came away with was that we'd probably never know all the possible pitfalls a user might run into, so including a code snippet at the bottom of each step that shows what the resulting code should look like would suffice for having to explain lots of details like this along the way. Maybe the hint could simply be to scroll down to check their work against the ending code snippet?

**Comment by seanforyou23** [comment]
Here's another idea. I know it's a goal to ensure even users new to react and programming can consume these courses, but maybe there's a better way of achieving that than making each intro tutorial potentially have to explain the same introductory concepts. For examples, do all of the beginner tutorials explain what a prop is?

I start to think it might make sense to have something like "up and running with react" pathway, where we can take time to carefully explain things like this in one place, so that absolute beginners can start there. This would allow us to explain those types of topics in more detail, while not adding "dead weight" to other beginner type tutorials that are _beginner_ in the sense of being introduced to a new component, not to programming as a whole.

A "beginner level" can mean a lot of different things depending on who you ask. Maybe offering a react primer course of some type would help streamline the other tutorial content. Thoughts?

**Comment by christiemolloy** [comment]
I think thats a really good idea to have an "up and running with react" pathway to not add dead weight to the component tutorials, I created a follow-up issue here to discuss this idea. #172

I also created another issue to be consistent about whether we use prop vs property across tutorials. #171
