### ISSUE TITLE
Make titles/descriptions for all Katacoda modules consistent

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#167]
@abigaeljamie maybe you could help us provide some naming conventions here:
i.e. sentence case for titles? / descriptions less than 2 sentences

You can see the examples of titles/descriptions here: https://www.katacoda.com/

**Comment by abigaeljamie** [comment]
Excellent details to focus on, Christie! I love that you brought up the sentence case. I heard that the UXD team decided to use sentence case for titles a while back, and I'm 100% onboard with that decision. It will eliminate confusion, too. It's not always easy to tell what should and should not be capitalized in title case titles. Yay for sentence case! So for example, "Infrastructure Automation & Configuration" becomes "Infrastructure automation & configuration." 

As for description length, I think anywhere from 1 to 3 sentences would be fine. As long as we don't have paragraphs for each, we should be good! Consistency is great, but I do think we should avoid using identical wording because it will all sort of blend for a user. For example, when I look at all the courses, I see a sea of "Learn how to...." Switching it up is fine as long as we have consistency in structure and some consistency in length (but we don't need to use the same words over and over again). A great resource we should consider using when choosing words for learning outcomes is Blooms Taxonomy: https://www.utica.edu/academic/Assessment/new/Blooms%20Taxonomy%20-%20Best.pdf 

I'm not sure if this would apply to all the courses, but when it comes to short descriptions like these, it's always good to kick off with the learning outcome (i.e., what the user will gain). So for example, instead of writing "Learn how to write HTML and CSS to improve your website's look and feel," we'd want to start with improving the website since that's the benefit to the user: "Improve your website's look and feel by learning HTML and CSS." (That was a sample one I made up.)   

Another thing to consider is tense. We want to stick with present tense whenever possible. So instead of "In this course, you'll follow the instructions to build a chart," we can instead go with "In this course, follow the instructions to build a chart."

I'm also noticing that a lot of the descriptions are missing periods. We'd want to include the punctuation for these when they get rewritten.

**Comment by christiemolloy** [comment]
**HTML/CSS:**
- Change `The Building Blocks for PatternFly Core` to `The building blocks of PatternFly`
- Change `This module will cover the guiding principles behind the three major parts of PatternFly Core—components, layouts, and demos and how they interact with each other.` 
to `Learn about components, layouts and demos.`

- Change `BEM Naming Principles` to `Variable naming principles`
- Change `This module will utilize BEM to create component and global variables and also override them.`
to `Create and override component and global variables by following BEM naming principles`

- Change `Modifier and Utility Classes` to `Modifiers and utilities`
- Change `Deep dive into modifiers.` 
to `Apply modifier and utility classes to achieve new variations`

- Change `PatternFly Layouts` to `Layouts`
- Change `This module will cover the seven different PatternFly layouts`
to `Learn how to use all seven of the layouts`

- Change `Overriding and Extending Variables` to `Override and extend variables`
- Change `Practice overriding and extending PatternFly variables to make new designs.`
to `Practice overriding and extending variables to achieve new designs`.

**React Basics:**
- Change `PatternFly React Components` to `PatternFly React basics`
- Change `Introduction to PatternFly React components`
to `Build your first PatternFly component`

- Change `PatternFly React Advanced` to `Customize PatternFly`
- Change `Advanced PatternFly React component usage`
to `Learn how to customize components in PatternFly`

**React Components**
- Change `PatternFly Filter Toolbar` to `Toolbar component with filter`
- Change `Building a PatternFly React Filter Toolbar`
to `Build a React toolbar that is filterable`

- Change `PatternFly React Table Basics` to `Table component: beginner`
- Change `Learn how to use PatternFly React Tables`
to `Build a React table with pagination`

React-Charts: (9 modules)
- Change all to sentence case
- Change all: `Introduction to PatternFly React [insert chart name] chart components`
to `Learn how to implement a React [insert chart name] chart `

@abigaeljamie do you mind looking over all of these changes and let me know if you have any more feedback :)

**Comment by abigaeljamie** [comment]
These are excellent, @christiemolloy ! They look and sound SO much better and aligned with the style we're going for. 

I only have two comments: 

1. Let's add the Oxford comma (Serial comma) after "layouts" so that it reads, "Learn about components, layouts, and demos." By using Oxford commas, we reduce the chance of ambiguity/misunderstanding. In the example sentences the Technical Writing Style Guide features, Oxford commas are used, too: http://stylepedia.net/style/#commas

2. The word "achieve" sounds more like "win" or "pull off." Is there a reason we go with "achieve" instead of "create" or "build" ?
