### ISSUE TITLE
Vertical re-size bug

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#210]
With the new vertical re-size feature, we are seeing a bug across all tutorials. The focus is going to the re-size, and off of the iframe. Which means:

- In the chart tutorials you can't hover over the chart to see the tooltips
- In the select component you can't click on the dropdown to expand the menu

The only way to re-focus onto the iframe is to re-size vertically, but theres no way for the user to know that now.

@gsoria

cc: @dlabrecq @dgutride

**Comment by seanforyou23** [comment]
Hi, in case it helps diagnose the problem, here is what I'm noticing:

Inside `#iframe_container` there exists an iFrame element along with `<div id="transparent-inner-box"></div>`. Because the transparent-inner-box is absolutely positioned over it's container, it's hijacking the pointer events.

When the window pane is resized, the following style is applied to the transparent inner container: `style="display: none;"` which has the effect of releasing any pointer event control back to its container.

One solution could be to apply `pointer-events: none` to `#transparent-inner-box`. Another solution could be to remove this element altogether or set the display property on init of the view instead of requiring users to resize their window to do this. I hope it helps!

**Comment by gsoria** [comment]
Thanks @seanforyou23 for the suggestion. We've added `pointer-events: none` to `#transparent-inner-box`. We've tested with https://katacoda.com/patternfly/courses/react-charts/area-chart and we can see the tooltips:

![Screen Shot 2019-12-10 at 10 49 29 AM](https://user-images.githubusercontent.com/5870211/70559519-ab595400-1b3b-11ea-9a2a-b433c5690889.png)

**Comment by christiemolloy** [comment]
Closing this issue now that the fix was implemented
